### ISSUE TITLE
NativeUIMenu hide after few seconds

### ISSUE THREAD

**Issue by Revyn112** [datWeazel/alt-V-NativeUI#1]
Inserted the codesnippet like writen in the readme and getting errors on clientside console.
NativeUI showed up only for a few seconds before its gone.

`[19:26:27][Error] [V8] Exception at includes/NativeUIMenu/modules/Container.mjs:30
[19:26:27][Error]              item.Draw(new Size(this.pos.X + offset.Width, this.pos.Y + offset.Height));
[19:26:27][Error] 00007FFB3090AAF0[19:26:27][Error]   RangeError: Maximum call stack size exceeded
    at Container.Draw (includes/NativeUIMenu/modules/Container.mjs:30:18)
    at NativeUI.render (includes/NativeUIMenu/NativeUI.mjs:597:24)
`

**Comment by datWeazel** [comment]
Could you post your code please? Didn't have any problems with this so far.

**Comment by Revyn112** [comment]
Nevermind. Error on my behaviour, cleaned up the whole clientside script, now it working without problems.
